create sequence hibernate_sequence start 1 increment 1;

create table answers_variant (question_id int8 not null, answers varchar(255), variants_answer_order int4 not null, primary key (question_id, variants_answer_order));

create table question (id int8 generated by default as identity, answer varchar(255), question varchar(255), primary key (id));

create table questions_list (test_id int8 not null, question int8, questions_order int4 not null, primary key (test_id, questions_order));

create table results_current_test (test_id int8 not null, best_result int4, test int8 not null, primary key (test_id, test));

create table results_tests (user_id int8 not null, best_result int4, test int8 not null, primary key (user_id, test));

create table test (id int8 generated by default as identity, author_id int8, author_name varchar(255), count_variants int4, is_active boolean, test_name varchar(255), primary key (id));

create table test_list_user (test_id int8 not null, list_user_id int8 not null, primary key (test_id, list_user_id));

create table user_role (user_id int8 not null, roles varchar(255));

create table usr (id int8 not null, course varchar(255), faculty varchar(255), firstname varchar(255), password varchar(255), surname varchar(255), username varchar(255), primary key (id));

alter table if exists test_list_user add constraint UK_4tjx3dfpx5n0uofttigxhw2lv unique (list_user_id);

alter table if exists answers_variant add constraint FKf0vgpv3skk9lmhyo44umnuvcy foreign key (question_id) references question;

alter table if exists questions_list add constraint FKl9xv45lrjose0cwjydbxvqbbj foreign key (test_id) references test;

alter table if exists results_current_test add constraint FK4to82r3tpcdx01tdmod58jibu foreign key (test_id) references test;

alter table if exists results_tests add constraint FKanbw2sfd8tffykmwifr3e0n7l foreign key (user_id) references usr;

alter table if exists test_list_user add constraint FKlevt4hi9r9y06shu0jm8buq2i foreign key (list_user_id) references usr;

alter table if exists test_list_user add constraint FK38fqsg4vtlxoao4c7r7ffj67v foreign key (test_id) references test;

alter table if exists user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;